from tkinter import *
class Calculadora:
  def __init__(self):
    self.janela = Tk()
    self.janela.title('calculadora')
    self.janela.geometry('250x250')
    self.frame1 = Frame(self.janela)
    self.frame1.pack(pady=5)
    self.valor1 = Label(self.frame1,text='valor 1')
    self.valor1.pack(side='left')
    self.caixa1 = Entry(self.frame1)
    self.caixa1.pack(side='left')
    self.frame2 = Frame(self.janela)
    self.frame2.pack()
    self.valor2 = Label(self.frame2,text='valor 2')
    self.valor2.pack(side='left')
    self.caixa2 = Entry(self.frame2)
    self.caixa2.pack(side='left')
    self.frame3 = Frame(self.janela)
    self.frame3.pack(pady=10)
    self.botaosoma = Button(self.frame3,text=' + ',command=self.soma)
    self.botaosoma.pack(side='left')
    self.botaosub = Button(self.frame3,text=' - ',command=self.sub)
    self.botaosub.pack(side='left')
    self.botaomult = Button(self.frame3,text=' * ',command=self.mult)
    self.botaomult.pack(side='left')
    self.botaodiv = Button(self.frame3,text=' / ',command=self.div)
    self.botaodiv.pack(side='left')
    self.frame4 = Frame(self.janela)
    self.frame4.pack()
    self.texto = Label(self.frame4, text='=')
    self.texto.pack(side='left')
    self.label = Label(self.frame4,text=' ')
    self.label.pack()
    self.frame5 = Frame(self.janela)
    self.frame5.pack()
    self.botaolimp = Button(self.frame5,text='Limpar',command=self.limpar)
    self.botaolimp.pack(side='left')
    self.botaosair = Button(self.frame5,text='Sair',command=self.sair)
    self.botaosair.pack(side='left',padx=5)
    self.janela.mainloop()
  def soma(self):
    self.v1 = int(self.caixa1.get())
    self.v2 = int(self.caixa2.get())
    self.sm = self.v1 + self.v2
    self.ts = str(self.sm)
    self.label.destroy()
    self.label = Label(self.frame4,text=self.ts)
    self.label.pack()
  def sub(self):
    self.v1 = int(self.caixa1.get())
    self.v2 = int(self.caixa2.get())
    self.s = self.v1 - self.v2
    self.ts = str(self.s)
    self.label.destroy()
    self.label = Label(self.frame4,text=self.ts)
    self.label.pack()
  def mult(self):
    self.v1 = int(self.caixa1.get())
    self.v2 = int(self.caixa2.get())
    self.m = self.v1 * self.v2
    self.tm = str(self.m)
    self.label.destroy()
    self.label = Label(self.frame4,text=self.tm)
    self.label.pack()
  def div(self):
    self.v1 = int(self.caixa1.get())
    self.v2 = int(self.caixa2.get())
    self.d = self.v1 / self.v2
    self.td = str(self.d)
    self.label.destroy()
    self.label = Label(self.frame4,text=self.td)
    self.label.pack()
  def limpar(self):
    self.label.destroy()
  def sair(self):
    self.janela.destroy()